references:
  node_defaults: &node_defaults
    working_directory: ~/repo
    docker:
      - image: circleci/node:11.4

version: 2
jobs:
  checkout_code:
    <<: *node_defaults
    steps:
      - checkout
      - persist_to_workspace:
          root: ~/repo
          paths:
            - .

  install:
    <<: *node_defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - restore-cache:
          key: yarn-{{ checksum "yarn.lock" }}
      - run: yarn install
      - save-cache:
          key: yarn-{{ checksum "yarn.lock" }}
          paths:
            - ~/repo/node_modules
      - persist_to_workspace:
          root: ~/repo
          paths:
            - node_modules

  test:
    <<: *node_defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - restore-cache:
          key: yarn-{{ checksum "yarn.lock" }}
      - run:
          name: Run yarn test
          command: yarn test

  lint:
    <<: *node_defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - restore-cache:
          key: yarn-{{ checksum "yarn.lock" }}
      - run:
          name: Run lint
          command: yarn eslint && yarn stylelint

  deploy:
    <<: *node_defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Deploy
          command: npx shipit production deploy

workflows:
  version: 2
  build:
    jobs:
      - checkout_code
      - install:
          requires:
            - checkout_code
      - test:
          requires:
            - install
      - lint:
          requires:
            - install
      - deploy:
          requires:
            - test
            - lint
          filters:
            branches:
              only: production
